### ISSUE TITLE
PNG Upload Issue 

### ISSUE THREAD

**Issue by tjs-364** [solgenomics/SMMID#25]
Structures that are uploaded as .png files are no longer displayed. An example is attached. 

![png upload issue](https://user-images.githubusercontent.com/58663786/101920988-793d6080-3b9a-11eb-902d-c8841ce87c5b.PNG)

**Comment by lukasmueller** [comment]
Fixed by adjusting the image_dir to the new location on /export/prod/public_smid/images (on file server that is backed up).
