### ISSUE TITLE
MS2 upload failed

### ISSUE THREAD

**Issue by tjs-364** [solgenomics/SMMID#26]
When trying to upload MS/MS data, clicking "upload" yields no response.

**Comment by lukasmueller** [comment]
Ryan, could you look at this issue, it may be an issue with the HTML of the spectrogram display in the page just above. Looks like a tag that is not closed or something like that? Please let me know if I should look at it as well.

**Comment by ryan-preble** [comment]
> Ryan, could you look at this issue, it may be an issue with the HTML of the spectrogram display in the page just above. Looks like a tag that is not closed or something like that? Please let me know if I should look at it as well.

Sure, I will take a look at it.

**Comment by lukasmueller** [comment]
this commit may fix this issue: d29be52
