### ISSUE TITLE
Adding MS data to preexisting SMIDs

### ISSUE THREAD

**Issue by tjs-364** [solgenomics/SMMID#5]
Currently, non-curators are not able to add MS data to preexisting SMIDs (SMIDs they did not create). Users should be able to do this. 

The following message is received when trying to do so: "The SMID with id 135 is (owned by ) not owned by you (8) and you cannot modify it."

**Comment by ryan-preble** [comment]
Fixed issue by removing a few lines of code in the update function under the controller that checks to see if the logged in user is the owner or a curator
